fixes for linux

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -1,31 +1,52 @@
+# Cross-platform .zshrc configuration for chezmoi
+# Automatically detects OS and adjusts paths
+
+# Detect OS type
+case "$(uname -s)" in
+  Darwin*)
+    OS_TYPE="macos"
+    ;;
+  Linux*)
+    OS_TYPE="linux"
+    ;;
+  *)
+    OS_TYPE="unknown"
+    ;;
+esac
+
 # If you come from bash you might have to change your $PATH.
 # export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
 
 export FZF_BASE=~/.fzf
 
-# Source z script
-. /opt/homebrew/etc/profile.d/z.sh
+# OS-specific configurations
+if [ "$OS_TYPE" = "macos" ]; then
+  # macOS-specific settings
+  if [ -f /opt/homebrew/etc/profile.d/z.sh ]; then
+    source /opt/homebrew/etc/profile.d/z.sh
+  fi
+else
+  # Linux-specific settings
+  if [ -f /usr/share/z/z.sh ]; then
+    source /usr/share/z/z.sh
+  elif [ -f $HOME/z/z.sh ]; then
+    source $HOME/z/z.sh
+  fi
+fi
 
 # Path to your Oh My Zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
 
-# Set name of the theme to load --- if set to "random", it will
-# load a random theme each time Oh My Zsh is loaded, in which case,
-# to know which specific one was loaded, run: echo $RANDOM_THEME
-# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
+# Set name of the theme to load
 ZSH_THEME="frisk2" # set by `omz`
 
 # Set list of themes to pick from when loading at random
-# Setting this variable when ZSH_THEME=random will cause zsh to load
-# a theme from this variable instead of looking in $ZSH/themes/
-# If set to an empty array, this variable will have no effect.
 # ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
 
 # Uncomment the following line to use case-sensitive completion.
 # CASE_SENSITIVE="true"
 
 # Uncomment the following line to use hyphen-insensitive completion.
-# Case-sensitive completion must be off. _ and - will be interchangeable.
 # HYPHEN_INSENSITIVE="true"
 
 # Uncomment one of the following lines to change the auto-update behavior
@@ -49,33 +70,31 @@ ZSH_THEME="frisk2" # set by `omz`
 # ENABLE_CORRECTION="true"
 
 # Uncomment the following line to display red dots whilst waiting for completion.
-# You can also set it to another string to have that shown instead of the default red dots.
-# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
-# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
 # COMPLETION_WAITING_DOTS="true"
 
 # Uncomment the following line if you want to disable marking untracked files
-# under VCS as dirty. This makes repository status check for large repositories
-# much, much faster.
+# under VCS as dirty.
 # DISABLE_UNTRACKED_FILES_DIRTY="true"
 
 # Uncomment the following line if you want to change the command execution time
 # stamp shown in the history command output.
-# You can set one of the optional three formats:
-# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
-# or set a custom format using the strftime function format specifications,
-# see 'man strftime' for details.
 # HIST_STAMPS="mm/dd/yyyy"
 
 # Would you like to use another custom folder than $ZSH/custom?
 # ZSH_CUSTOM=/path/to/new-custom-folder
 
-# Which plugins would you like to load?
-# Standard plugins can be found in $ZSH/plugins/
-# Custom plugins may be added to $ZSH_CUSTOM/plugins/
-# Example format: plugins=(rails git textmate ruby lighthouse)
-# Add wisely, as too many plugins slow down shell startup.
-plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-completions fzf zsh-interactive-cd docker colored-man-pages)
+# Base plugins that work universally
+plugins=(git fzf zsh-interactive-cd docker colored-man-pages)
+
+# Check for plugin existence before adding to the list
+for plugin in zsh-autosuggestions zsh-syntax-highlighting zsh-completions; do
+  if [ -d "${ZSH_CUSTOM:-$ZSH/custom}/plugins/$plugin" ] || [ -d "$ZSH/plugins/$plugin" ]; then
+    plugins+=($plugin)
+  else
+    echo "[oh-my-zsh] plugin '$plugin' not found. Install with:"
+    echo "git clone https://github.com/zsh-users/$plugin ${ZSH_CUSTOM:-$ZSH/custom}/plugins/$plugin"
+  fi
+done
 
 source $ZSH/oh-my-zsh.sh
 
@@ -87,53 +106,89 @@ source $ZSH/oh-my-zsh.sh
 # export LANG=en_US.UTF-8
 
 # Preferred editor for local and remote sessions
-# if [[ -n $SSH_CONNECTION ]]; then
-#   export EDITOR='vim'
-# else
-#   export EDITOR='nvim'
-# fi
+if [[ -n $SSH_CONNECTION ]]; then
+  export EDITOR='vim'
+else
+  export EDITOR='nvim'
+fi
 
 # Compilation flags
 # export ARCHFLAGS="-arch $(uname -m)"
 
-# Set personal aliases, overriding those provided by Oh My Zsh libs,
-# plugins, and themes. Aliases can be placed here, though Oh My Zsh
-# users are encouraged to define aliases within a top-level file in
-# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
-# - $ZSH_CUSTOM/aliases.zsh
-# - $ZSH_CUSTOM/macos.zsh
-# For a full list of active aliases, run `alias`.
-#
-# Example aliases
-# alias zshconfig="mate ~/.zshrc"
-# alias ohmyzsh="mate ~/.oh-my-zsh"
+# Aliases
 alias python="python3"
 
-export PYENV_ROOT="$HOME/.pyenv"
-export PATH="$PYENV_ROOT/bin:$PATH"
-eval "$(pyenv init --path)"
-eval "$(pyenv init -)"
-eval "$(pyenv virtualenv-init -)"
-
-export JAVA_HOME=$(/usr/libexec/java_home -v 23)
-export PATH="$JAVA_HOME/bin:$PATH"
-export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
-
-
-autoload -U +X bashcompinit && bashcompinit
-complete -o nospace -C /opt/homebrew/bin/terraform terraform
-
-. "$HOME/.local/bin/env"
-eval "$(uv generate-shell-completion zsh)"
-
-# fnm
-FNM_PATH="/Users/dashvallance/Library/Application Support/fnm"
-if [ -d "$FNM_PATH" ]; then
-  export PATH="/Users/dashvallance/Library/Application Support/fnm:$PATH"
-  eval "`fnm env`"
+# Python environment setup
+if [ -d "$HOME/.pyenv" ]; then
+  export PYENV_ROOT="$HOME/.pyenv"
+  export PATH="$PYENV_ROOT/bin:$PATH"
+  command -v pyenv >/dev/null && eval "$(pyenv init --path 2>/dev/null || true)"
+  command -v pyenv >/dev/null && eval "$(pyenv init - 2>/dev/null || true)"
+  command -v pyenv >/dev/null && eval "$(pyenv virtualenv-init - 2>/dev/null || true)"
 fi
 
-# fnm autocomplete
-eval "$(fnm env --use-on-cd --shell zsh)"
+# Java setup - OS specific
+if [ "$OS_TYPE" = "macos" ]; then
+  # macOS Java configuration
+  if [ -x /usr/libexec/java_home ]; then
+    export JAVA_HOME=$(/usr/libexec/java_home -v 23 2>/dev/null || /usr/libexec/java_home 2>/dev/null)
+    export PATH="$JAVA_HOME/bin:$PATH"
+    export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
+  fi
+elif [ "$OS_TYPE" = "linux" ]; then
+  # Linux Java configuration - uncomment and adjust if needed
+  # Try to find Java automatically
+  # Temporarily set NULL_GLOB to prevent errors when patterns don't match
+  setopt NULL_GLOB 2>/dev/null || true
+  for java_path in /usr/lib/jvm/default-java /usr/lib/jvm/java-[0-9]*-openjdk* /usr/lib/jvm/java-[0-9]*-oracle; do
+    if [ -d "$java_path" ]; then
+      export JAVA_HOME="$java_path"
+      export PATH="$JAVA_HOME/bin:$PATH"
+      break
+    fi
+  done
+  # Reset to default globbing behavior
+  unsetopt NULL_GLOB 2>/dev/null || true
+fi
 
+# Terraform completion
+if command -v terraform &>/dev/null; then
+  autoload -U +X bashcompinit && bashcompinit
+  complete -o nospace -C $(which terraform) terraform
+fi
+
+# uv completion - if installed
+if command -v uv &>/dev/null; then
+  eval "$(uv generate-shell-completion zsh 2>/dev/null || true)"
+fi
+
+# Environment file - check if exists before sourcing
+if [ -f "$HOME/.local/bin/env" ]; then
+  . "$HOME/.local/bin/env"
+fi
+
+# fnm (Fast Node Manager) - OS specific paths
+if [ "$OS_TYPE" = "macos" ]; then
+  FNM_PATH="/Users/dashvallance/Library/Application Support/fnm"
+else
+  FNM_PATH="$HOME/.local/share/fnm"
+fi
+
+# Load fnm if it exists at the detected path
+if [ -d "$FNM_PATH" ]; then
+  export PATH="$FNM_PATH:$PATH"
+  command -v fnm &>/dev/null && eval "$(fnm env 2>/dev/null || true)"
+
+  # fnm autocomplete
+  command -v fnm &>/dev/null && eval "$(fnm env --use-on-cd --shell zsh 2>/dev/null || true)"
+fi
+
+# GitHub username
 export GITHUB_USERNAME=dashdotme
+
+# Note for setup:
+# Run the following commands to install missing plugins:
+#
+# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
+# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
+# git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-completions
